title: <p align="center">Abhardeep Chandra Paul
logo: assets/img/me.jpeg
description:
  <p align="center">
  <a href="https://www.linkedin.com/in/abhradeepchandrapaul">LinkedIn</a> |
  <a href="https://github.com/Abhra-deep">GitHub</a>
show_downloads: true
theme: jekyll-theme-minimal
