title: <p align="center">Abhardeep Chandra Paul
logo: assets/img/me.jpeg
description:
  <p align="center">
  <a href="https://www.linkedin.com/in/abhradeepchandrapaul">LinkedIn</a> |
  <a href="https://github.com/Abhra-deep">GitHub</a>
  <br>   
  I like to work on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  Motivated fresher specializing in Data Science, Big Data, Machine Learning, and NLP,
  with a passion for real-time analytics and scalable AI solutions.
  Skilled in Python, SQL, TensorFlow, PyTorch, and cloud platforms like AWS and GCP.
  Proficient in handling large-scale datasets, focusing on language modeling, recommendation systems, and semantic analysis.
  Hold a PG Diploma in Data Science (IIIT Bangalore) and a B.Tech in Electronics & Communication (8.79 CGPA).
  Experienced through projects in AdTech-related data analysis and machine learning models,
  aiming to drive impactful insights and innovative solutions in the data science domain.
  <br>
  </p>
show_downloads: true
theme: jekyll-theme-minimal
