title: Abhardeep Chandra Paul
logo: assets/img/me.jpeg
description:
  
  <a href="https://www.linkedin.com/in/abhradeepchandrapaul">LinkedIn</a> |
  <a href="https://github.com/Abhra-deep">GitHub</a>
  <br>   
  I like to work on Data Science, Big Data, Spark, Machine Learning & NLP.
  Skilled in Python, SQL, TensorFlow, and cloud platforms like AWS.
  Hold a PG Diploma in Data Science (IIIT Bangalore) and a B.Tech (8.79 CGPA).
  Experienced in AdTech projects, focusing on real-time analytics and AI solutions.
  <br>
  </p>
show_downloads: true
theme: jekyll-theme-minimal
