title: <p align="center">Abhardeep Chandra Paul
logo: assets/img/me.jpeg
description:
  <p align="center">
  <a href="https://www.linkedin.com/in/abhradeepchandrapaul">LinkedIn</a> |
  <a href="https://github.com/Abhra-deep">GitHub</a>
  <br>   
  I like to work on Data Science, Big Data, Spark, Machine Learning & NLP-related problems.
  Motivated fresher skilled in Python, SQL, TensorFlow, PyTorch, and cloud platforms like AWS and GCP.
  Proficient in handling large-scale datasets, focusing on language modeling and semantic analysis.
  Hold a PG Diploma in Data Science (IIIT Bangalore) and a B.Tech in Electronics & Communication (8.79 CGPA).
  Experienced through projects in AdTech data analysis and machine learning, passionate about real-time analytics and scalable AI solutions..
  <br>
  </p>
show_downloads: true
theme: jekyll-theme-minimal
