title: <p align="center">Abhardeep Chandra Paul
logo: /assets/img/logo.png
description: 
show_downloads: true
theme: jekyll-theme-minimal

social_links:
  linkedin: https://www.linkedin.com/in/abhradeepchandrapaul
  github: https://github.com/Abhra-deep
